import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";

export default function Services() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Suganya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Services</main>
    </div>
  );
}
